# Generated by Django 4.2.10 on 2024-02-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
